### ISSUE TITLE
PostgreSQL version support

### ISSUE THREAD

**Issue by kuromukira** [rdagumampan/yuniql#47] opened 2020-01-21 09:19 UTC
![image](https://user-images.githubusercontent.com/9804927/72791327-16856280-3c72-11ea-8a3c-0e0f8ff556c9.png)
do you support version 11 or 12 with the [azure pipelines task](https://marketplace.visualstudio.com/items?itemName=rdagumampan.yuniql-azdevops-extensions&targetId=7dc48a05-88c9-472a-85eb-d587d8428c8f)?

**Comment by rdagumampan** [comment] 2020-01-21 14:33
Hi @kuromukira, thanks for reaching out. No, I have yet to support PostgreSql in the Az DevOps Task. I think in the next week or two, I would be able to implement this.

I just hit a hard wall when dynamically loading plugins in .NET Core 3.0 self-contained app. But I think figured it now and just reviewing the platform tests. The platform tests have passed on v9.6 and v12.1.

**Comment by kuromukira** [comment] 2020-01-21 16:27
Woah. That's really great! Can't wait for the release!

**Comment by rdagumampan** [comment] 2020-01-27 06:17
@kuromukira, good day. The latest build of az devops task now supports PostgreSql and MySql. Can you test this if it works out for you. Please use connection string in this format.

```console
Server={HOST};Port=5432;Database={DATABASENAME};User Id={USERID};Password={USERPASSWORD};
```

![image](https://user-images.githubusercontent.com/5895952/73153608-af820680-40d4-11ea-849b-9b4009bc87f1.png)

References:
https://www.connectionstrings.com/postgresql/

**Comment by kuromukira** [comment] 2020-01-27 08:34
Hi @rdagumampan , thank you so much. Will try implementing this in one of our upcoming milestones. Will let you know. Thank you.

**Comment by kuromukira** [comment] 2020-01-29 10:01
Hi @rdagumampan 

I'm getting this error with `Run Yuniql`
![image](https://user-images.githubusercontent.com/9804927/73346775-67740700-42c1-11ea-8ae0-991ce9a0aaa4.png)

Any ideas?

**Comment by rdagumampan** [comment] 2020-01-29 10:26
Hi, can you shared the full log?

**Comment by rdagumampan** [comment] 2020-01-29 10:58
Hi @kuromukira, I just test run again against empty pgsql database and it went OK. I created a pgsql instance on https://www.elephantsql.com and create release pipeline.

Here my task setup:
![image](https://user-images.githubusercontent.com/5895952/73351133-ad63a780-428e-11ea-94a0-d1fc31020749.png)

Results:
![image](https://user-images.githubusercontent.com/5895952/73351091-9755e700-428e-11ea-8132-746198f748e4.png)

**Comment by kuromukira** [comment] 2020-01-29 16:14
Hi @rdagumampan 

Sharing the az pipeline log (from our release pipeline)
![image](https://user-images.githubusercontent.com/9804927/73374455-2e558a00-42f5-11ea-8d8a-86ea3f28405a.png)

The `platformdb-migration.sql` was generated through our build pipeline and was uploaded as a build artifact.
`dotnet ef migrations script -o $(Build.ArtifactStagingDirectory)/migrations/platformdb-migration.sql`

**Comment by rdagumampan** [comment] 2020-01-29 17:28
@kuromukira, got it thanks! At a minimum, yuniql requires the main db migration directory to have these conventions. You can copy our sample or use `yuniql` CLI to generate this.

![image](https://user-images.githubusercontent.com/5895952/73380299-131e5680-42c4-11ea-99f5-7f775c3523fb.png)

You can create this structure in several ways:
**Option 1:** Clone yuniql repo and copy the structure from our samples for pgsql. See this https://github.com/rdagumampan/yuniql/tree/master/samples/basic-postgresql-sample. You can commit this as separate git repo and place your baseline scripts in v0.00 folder.

Option 2: Install yuniql locally to setup the structure. You can do this like this if you have choco.

```console
choco install yuniql --version 0.328.0

cd c:\temp
md testdb

yuniql init
```

You can also do `dotnet tool install -g yuniql.cli` or download directly from github/releases here 
https://github.com/rdagumampan/yuniql/releases/download/latest/yuniql-cli-win-x64-latest.zip

I hope this works out for you. 
HTH/Rodel

**Comment by rdagumampan** [comment] 2020-01-29 17:59
If you intend to you yuniql as primarily an execution engine, you create structure before you run the migration:
1. Add task "Command Line", before `Run YUNIQL` task
2. Add the following scripts

```console
#requires .netcore 3.0
dotnet tool install -g yuniql.cli

cd  $(Build.ArtifactStagingDirectory)/migrations
yuniql init

dotnet ef migrations script -o $(Build.ArtifactStagingDirectory)/migrations/v0.00/platformdb-migration.sql
```

This is not the ideal usage fore yuniql but it may work for you :) 
HTH/Rodel

**Comment by kuromukira** [comment] 2020-01-31 03:05
Hi @rdagumampan, thank you for the suggestions.

I have tried your suggestion [here](https://github.com/rdagumampan/yuniql/issues/47#issuecomment-579882342) and my release pipe failed with the same error. Below are my build and release pipeline setups:

Build Pipeline:
![image](https://user-images.githubusercontent.com/9804927/73509178-30186e00-4419-11ea-9cd2-7947746c0ae9.png)

Release Pipeline:
![image](https://user-images.githubusercontent.com/9804927/73509262-8685ac80-4419-11ea-90b4-0dd81720cf3e.png)

**Comment by kuromukira** [comment] 2020-01-31 03:37
one more thing, you seem to have a value for
![image](https://user-images.githubusercontent.com/9804927/73510724-13326980-441e-11ea-90e2-9b24206ddd8f.png)

**Comment by rdagumampan** [comment] 2020-01-31 06:01
> one more thing, you seem to have a value for
> ![image](https://user-images.githubusercontent.com/9804927/73510724-13326980-441e-11ea-90e2-9b24206ddd8f.png)

Hi @kuromukira,

The values here are to demonstrate token replacement feature. We have described some of the use cases here https://github.com/rdagumampan/yuniql/wiki/How-to-apply-token-replacement. You can leave this blank.

**Comment by rdagumampan** [comment] 2020-01-31 06:08
I think you are very close to getting this to work :) 

Try to change the value of `Target Workspace` in the `Run YUNIQL` task. This parameter refers to root directory where the base structure is placed. Try these value: `$(System.DefaultWorkingDirectory)/_db-ci/Migration Script/migrations`

**Comment by rdagumampan** [comment] 2020-01-31 06:15
Would be helpful maybe if you try to simulate this locally. We can do it like this.

```console
choco install yuniql --version 0.328.0

cd c:/temp
md testdb
cd testdb

yuniql init
dotnet ef migrations script -o "c:/temp/testdb/v0.00/platformdb-migration.sql"
```

Run migrations
```console
yuniql run -p "c:/temp/testdb" -c "<your-connection-string>"
yuniql info "<your-connection-string>"
```

**Comment by kuromukira** [comment] 2020-01-31 06:44
Hi @rdagumampan 

[This](https://github.com/rdagumampan/yuniql/issues/47#issuecomment-580595124) fixed the issue I've been having. Now I think my problem is with the connection string.

**Comment by rdagumampan** [comment] 2020-01-31 06:51
@kuromukira, goo to hear. Try to use connection string in this format `Server={HOST_SERVER};Port=5432;Database={DB_NAME};User Id={USER_ID};Password={USER_PASSWORD};
`

Reference:
https://www.connectionstrings.com/postgresql/

HTH/Rodel

**Comment by kuromukira** [comment] 2020-01-31 07:03
@rdagumampan it seems that the task does not pick up the connection string if it's set as a secret in the variables tab of the release pipeline. I managed to make it work by adding it directly to the task and by adding as a plain text variable

Additional question, 
![image](https://user-images.githubusercontent.com/9804927/73518698-0459b000-443a-11ea-961a-14e0b2c6ab8a.png)
Did this create a new table?

**Comment by rdagumampan** [comment] 2020-01-31 07:13
Yuniql will attempt to create this table `__yuniqldbversion` once. This is used for tracking versions already applied in the target database. When your first run failed due to connection issues, this will not be created. Appreciate if you can verify, I think I covered this with test.

**Comment by rdagumampan** [comment] 2020-01-31 07:19
> @rdagumampan it seems that the task does not pick up the connection string if it's set as a secret in the variables tab of the release pipeline. I managed to make it work by adding it directly to the task and by adding as a plain text variable

Hmm.. I just tried to reproduce and it seems to have worked fine. 
![image](https://user-images.githubusercontent.com/5895952/73519753-29cac780-4402-11ea-86e0-24759166cb55.png)

![image](https://user-images.githubusercontent.com/5895952/73519846-672f5500-4402-11ea-9c7c-50f713ab9866.png)

**Comment by kuromukira** [comment] 2020-01-31 07:27
> NOTE: If this runs successfully, your next run will skip `v0.00` because the DB already runs in this version of your ef generated schema. If your intent for recreate db every time, you will have to create cleanup script and place in `_erase` directory. Then you can run `yuniql erase -p <your-db-project-directory> -p <your-connection-string>`
In my release pipeline, the `v0.00` is constant and will remain unchanged regardless of the number of releases created.

And in relation to
> Yuniql will attempt to create this table `__yuniqldbversion` once. This is used for tracking versions already applied in the target database. When your first run failed due to connection issues, this will not be created. Appreciate if you can verify, I think I covered this with test.
Will it fail if it detects that the version created every release remains unchanged? Idk why but here in the pipeline, it gets connection timeout. The connection string is working fine when connecting via pgAdmin and the asp.net core APIs themselves.

**Comment by rdagumampan** [comment] 2020-01-31 08:04
On connection timeout issue, it maybe a firewall issue. When i test in Azure SQL i have to grant access to az devops, it may be the same for AWS. I can try later at home. Is it Amazon RDS for PostgreSql? Or Aurora?

On v0.00, every version folder is an atomic version of your database. V0.00 is what we called baseline version. When it runs OK, a row is created in __yuniqldbversion table. The next time you run migration, yuniql checks the latest changes applied in target db and whats newer locally. It expects at least a version folder higher than v0.00 or it will do nothing. The sql dump from ef in v0.00 while an updated one will not be executed.

You may dynamically generate the version folder by using the Build variables in az devops.

**Comment by kuromukira** [comment] 2020-01-31 08:18
@rdagumampan i see. it's probably an issue with AWS RDS for PgSQL.

**Comment by rdagumampan** [comment] 2020-01-31 11:34
Looks like something is broken in your directory structure. Version folders have to be in this format  ‘v{major}.{minor}. This error i related to that.

With connection timeout, let me know if this actually a firewall issue. HTH

**Comment by kuromukira** [comment] 2020-02-03 01:27
Hi @rdagumampan , just an update, we decided to use the `context.Database.Migrate` instead (_for now_). There might be some performance bottlenecks tho. I will use this issue thread as reference in the future. Thank you.

**Comment by rdagumampan** [comment] 2020-02-03 05:25
@kuromukira, thanks for trying. I will simulate your case anyway this week as I think w can find nice flavor between `ef` and `yunql`. You can do code-first migrations, then dump sql file so you can further optimize and use `yuniql` as execution engine in pipeline.

I will keep you posted here when I got this to work and how.

**Comment by kuromukira** [comment] 2020-02-03 07:10
@rdagumampan thank you. keep up the great work you have here. I will revisit this again as I'm pretty sure we will be needing this someday.

**Comment by kuromukira** [comment] 2020-02-05 03:11
Hi @rdagumampan, I just confirmed it might be a firewall issue with AWS RDS. I recently tried creating a build pipeline that executes `dotnet ef database update` and got the same error with the `run yuniql` task regarding npgsql connection timeout.

**Comment by rdagumampan** [comment] 2020-02-05 12:47
@kuromukira thanks for following through. Good to hear you have had progress. I have yet to post my notes here but yes I did created Amazon RDS PostgreSql and I was able to repro your connection timeout issue. I have set the firewal to Anywhere and it all works fine. I don't think this is ideal to use Anywhere but I will look at IP Range used by Azure DevOps Agents.

Meanwhile, I have made progress in finding the ef+yuniql flavor here. I find this very interesting use case where we use code-first for development, generate scripts for migration, review and optimize scripts and run migration with yuniql. I have to to put this in CI/CD but this should describe the flow to you.

https://github.com/rdagumampan/yuniql/tree/master/samples/postgresql-efcore-sample

**Comment by rdagumampan** [comment] 2020-02-05 13:00
> Question tho, what if I don't change the version folder for `Yuniql` (eg will remain as v0.00)? Will it still execute the migration?

`yuniql` will skip this folder because it assumes that version has already been applied to target database. Imagine if that version is creating a table Employee, it will fail if it attempts to create a new employee table. If you are recreating the database every pipeline run, you can create cleanup scripts and place in `_erase` directory and use `yuniql erase` to execute before you run the migration. This would erase all tables in target db every time. With this `v0.00` will always be executed.

If this is not the case, the best approach is to dynamically create the version directory using `Build.BuildNumber` variable. You just have to test it out first what the value it generates. I think this is the right value of your Release name format under Options  `v0.0.$(rev:r)`

![image](https://user-images.githubusercontent.com/5895952/73843864-c389de80-481f-11ea-9c8b-70610069d934.png)

Then in your CommandLine Task, use `md $(Build.BuildNumber)`

**Comment by kuromukira** [comment] 2020-02-05 14:35
hi @rdagumampan , thanks. that is exactly the use-case i was doing. ef core code-first migrations. so far,  yuniql works as intended but only through GCP CloudSQL (_which we decided to move to_). i also got the $BuildNumber and $rev working for the folder names just to make sure yuniql executes the migration.

**Comment by rdagumampan** [comment] 2020-02-06 05:23
@kuromukira , i have a working sample now to cover efcore+yuniql. See notes below. HTH

### AWS Firewall settings, allow Anywhere for testing
![image](https://user-images.githubusercontent.com/5895952/73908026-a77e4f80-48a8-11ea-89ed-519e0d3cff9e.png)

### Accessible via pgAdmin
![image](https://user-images.githubusercontent.com/5895952/73907869-2de66180-48a8-11ea-883c-2378237f214e.png)

### Azure DevOps Release Pipeline

#### Options
![image](https://user-images.githubusercontent.com/5895952/73908078-d1d00d00-48a8-11ea-87ce-0d99baac431a.png)

#### Tasks
![image](https://user-images.githubusercontent.com/5895952/73908048-bb29b600-48a8-11ea-9863-b432e62be5ae.png)

#### Powershell Inline Statements

```powershell
#install cli tools
dotnet tool install -g yuniql.cli
dotnet tool install --global dotnet-ef

#build the ef project
cd $(System.DefaultWorkingDirectory)\_rdagumampan_yuniql\samples\postgresql-efcore-sample
dotnet build efsample.csproj

#prepare yuniql required dir structure
md _db
cd _db
yuniql init

#create migration script from the last known migration id (not based on actual db history)
cd $(System.DefaultWorkingDirectory)\_rdagumampan_yuniql\samples\postgresql-efcore-sample
dotnet ef migrations list --no-build >> current_efversions.txt

#show the content of current_efversions.txt
Get-Content -Path ".\current_efversions.txt"

$fromVersion = Get-Content -Path ".\current_efversions.txt" | Select-Object -Skip 1 | Select-Object -Last 2 | Select-Object -First 1
Write-Host "Scripting migration from: $fromVersion"
dotnet ef migrations script $fromVersion  -o $(System.DefaultWorkingDirectory)\_rdagumampan_yuniql\samples\postgresql-efcore-sample\_db\$(Release.ReleaseName)\migrate.sql --no-build
Remove-Item .\current_efversions.txt

#show the content of migrate.sql
Get-Content -Path $(System.DefaultWorkingDirectory)\_rdagumampan_yuniql\samples\postgresql-efcore-sample\_db\$(Release.ReleaseName)\migrate.sql

#run migrations to database
#yuniql run -p $(System.DefaultWorkingDirectory)\_rdagumampan_yuniql\samples\postgresql-efcore-sample\_db --platform postgresql -c "$(AzPostgreSqlDemoDatabase)" --debug
#yuniql info --platform postgresql -c "$(AzPostgreSqlDemoDatabase)" --debug

cd $(System.DefaultWorkingDirectory)\_rdagumampan_yuniql\samples\postgresql-efcore-sample\_db
dir 
```

**Comment by kuromukira** [comment] 2020-02-06 05:45
hi @rdagumampan , thank you for the example.

**Comment by rdagumampan** [comment] 2020-02-06 06:08
> hi @rdagumampan , thank you for the example.

Np. If the fix above is so far enough to get you going, appreciate if you can give the repo a star :). It'll be helpful when I start the campaign after release.

This is not robust solution as I rely on every migration run to be successful when I pickup the `fromVersion` . I wish `efcore` exposes API to capture the current version of database from `EFMigrationHistory` table so we can get the actual last migration succesfuly applied.

As alternative, you can expose an endpoint in your Web API to get last migration applied by `efcore` in your target database. We use that instead as value of `from` when doing `ef migrations script`.

HTH

**Comment by kuromukira** [comment] 2020-02-21 18:13
hi @rdagumampan . I encountered a problem earlier on one of our release pipelines for our staging environment. Seems like there's an update to the table structure of **__yuniqldbversion**? That caused the pipeline to fail somehow. Will get to test this again after 2 weeks during the next milestone release to staging. Will keep you posted.

**Comment by rdagumampan** [comment] 2020-02-23 00:51
@kuromukira lost track of our discussions here. I should have ping you but this is one of the breaking changes in the last release `v0.350.0`. I have renamed the columns, drop some and add new ones in this tracking table. I hope that this is final but I'll keep you posted should there be breaking change again.

**Comment by kuromukira** [comment] 2020-02-23 01:58
@kuromukira thank you.

**Comment by rdagumampan** [comment] 2020-05-18 20:21
@kuromukira , if you are still using yuniql in your project, I will be releasing a beta release this week. There are many breaking changes in this build. FYI.

I'm closing this case now. Please file new ticket should you still have issues. Thanks for trying.

**Closed by rdagumampan** 2020-05-18 20:21 UTC
Labels: implementing

**Comment by kuromukira** [comment] 2020-05-19 00:42
Hi @rdagumampan , yup I am still using yuniql (_it's very good btw_). Thank you for informing me about the beta release. I will keep you posted for any issues from the breaking changes.

**Comment by rdagumampan** [comment] 2020-05-27 10:38
@kuromukira ,

FYI, I have just release v0.465.0 this morning. This is a BETA RELEASE and maybe have breaking changes on your pipelines. Please refer to this release note and create ticket if you found an issue.

https://github.com/rdagumampan/yuniql/releases/tag/v0.465.0

Thanks for your interest with yuniql.
Cheers, Rodel

**Comment by kuromukira** [comment] 2020-05-27 10:42
hi @rdagumampan , we are on a 2 week-cycle for each milestone. last weekend we had a successful deployment to our staging using yuniql for db migrations. no problems so far. we will be able to test again next next weekend. will let you know if there are any issues.

**Comment by somilygz** [comment] 2021-04-28 17:20
Hi @rdagumampan,  I am implementing Erease Yuniql and I get the following error **This NpgsqlTransaction has completed; it is no longer usable**, the process deletes my tables in PostgreSQL (HyperScale) but flag that error.
My tables contain large amounts of data and take a long time to delete.
I am trying to delete more than 300 tables.

My script is similar to this wuth the all 300 tables.
BEGIN;
DROP TABLE IF EXISTS dd_dyp_pro.isrretencionesusopt CASCADE;
COMMIT;
BEGIN;
DROP TABLE IF EXISTS dd_dyp_pro.ivapfpagodefinitivopt CASCADE;
COMMIT;
BEGIN;
DROP TABLE IF EXISTS dd_dyp_pro.ivaprestacionservdigitales CASCADE;
COMMIT;
BEGIN;
DROP TABLE IF EXISTS dd_dyp_pro.ivaretencionesusopt CASCADE;
COMMIT;
BEGIN;
DROP TABLE IF EXISTS dd_dyp_pro.pd_pago CASCADE;
COMMIT;

**Comment by Naimishah** [comment] 2021-07-15 14:16
![image](https://user-images.githubusercontent.com/31841996/125802838-57429d95-d021-471b-b56e-f7ae1059981e.png)
Hi @rdagumampan while setting up PostgreSQL Azure release am facing this error 
below is my connection string please help me 
Server=ella.db.elephantsql.com, Port=5432;Database=wlwvedlt; User ID=wlwvedlt; Password=G7HaU-zTjvgd5kI1F3t576XruLSiipvd;
