### ISSUE TITLE
-- environment argument does not work

### ISSUE THREAD

**Issue by developertrudexia** [rdagumampan/yuniql#214] opened 2021-09-10 06:43 UTC
dev.azure.com pipeline is being used. When the --environment argument is not used the scripts that exist in the v0.00 directory are found and execute fine. We have now moved these scripts to v0.00\_DEV folder and with the --environment DEV argument, the scripts are now not found:

Running yuniql v1.1.55 for windows-x64
Copyright 2019 (C) Rodel E. Dagumampan. Apache License v2.0
Visit https://yuniql.io for documentation & more samples

INF   2021-09-10 03:48:57Z   Run configuration: 
{
  "isInitialized": true,
  "workspace": "D:\\a\\1\\s\\sql",
  "platform": "postgresql",
  "connectionString": "<sensitive-data-redacted>",
  "isAutoCreateDatabase": true,
  "targetVersion": "v0.00",
  "tokens": [],
  "isVerifyOnly": false,
  "bulkSeparator": ",",
  "bulkBatchSize": 0,
  "commandTimeout": 30,
  "isDebug": true,
  "appliedByTool": "yuniql-cli",
  "appliedByToolVersion": "1.1.55.0",
  "environment": "DEV",
  "metaSchemaName": null,
  "metaTableName": null,
  "isContinueAfterFailure": false,
  "transactionMode": "session",
  "isRequiredClearedDraft": false,
  "isForced": false
}

INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql\v0.00\_DEV
INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql
INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql\v0.00\_DEV\100-predata
INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql
INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql\v0.00\_DEV\200-data
INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql
INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql\v0.00\_DEV\300-postdata
INF   2021-09-10 03:48:59Z   Found 0 script files on D:\a\1\s\sql

**Comment by rdagumampan** [comment] 2021-09-12 06:43
@developertrudexia, thanks for reaching out. Can you try to reorganize your scripts as its sampled here 'https://github.com/rdagumampan/yuniql-tutorials/tree/master/yuniql-environment-aware/v0.01'. Let me know if this works out for you. Again, thanks for the feedback. HTH/Rodel

**Comment by developertrudexia** [comment] 2021-09-12 09:20
Hi

Thanks. We do have our scripts organised like this - we use _dev _tst _prd.

When we run the command line in powershell we have to make the following changes:

  *    the environment variable must be lower case
  *   The , character for the —bulk-separator must be encapsulated by “ or escaped by ‘ character

The default —bulk-seperator does not allow preceding it by the escape character nor encapsulating within “ characters.  When not using — environment argument, the scripts do execute (when they are sitting at the root level or the version ie v0.00

The challenge we have now in the azure devops pipeline is altering the —bulk-seperator character argument.

I think the default setting for — bulk-separating is causing the additional arguments ie — environment to be ignored (which are entered after the ‘ — bulk-separator , ‘ argument.




See my schedule and book a time here<https://trudexia.pipedrive.com/scheduler/olbyZ2FL/quick-catchup-with-paul-dimatteo> for a quick catchup


See my schedule and book a time here<https://trudexia.pipedrive.com/scheduler/Ml01RMFe/trudexia-workshop> for a workshop


See my schedule and book a time here<https://trudexia.pipedrive.com/scheduler/kOqPMEtb/trudexia-meeting-face-to-face-paul-dimatteo> face-to-face


See my schedule and book a time here<https://trudexia.pipedrive.com/scheduler/82k5lqCm/meeting-with-paul-dimatteo-trudexia> for an online meeting


See my schedule and book a time here<https://trudexia.pipedrive.com/scheduler/qlJ1jpF0/lunch-with-paul> for lunch




Paul Di Matteo
Founder
Level 26, 44
Market Street Sydney,
NSW 2000 Australia
Tel: +61 2 9089 8879
Fax: +61 2 9089 8880
Mobile: +61 421 898 555
***@***.***
www.trudexia.com
________________________________

**Comment by rdagumampan** [comment] 2021-09-12 21:12
@developertrudexia , thanks for more information. I sense that you maybe have experienced multiple issues and I think some of them are as designed and some maybe new bug :).

1. The environment variable must be lower case. -> This is new to me and I'll run some tests on this. I have been using CAP ENV all the time in our tests. 
2.  The , character for the —bulk-separator must be encapsulated by “ or escaped by ‘ character. -> Yes I think it works this way when using Powershell. I'll also write some tutorials on this just to verify. Thanks for input.
3.  The default —bulk-seperator does not allow preceding it by the escape character nor encapsulating within “ characters. 
4. When not using — environment argument, the scripts do execute (when they are sitting at the root level or the version ie v0.00 -> When using `--environment`, it assumes that each version directory is specially organized to have environment directory such as `_dev` or `_prod`. This maybe an issue I agree if some version dirs have environment dir and some have not.
5. The challenge we have now in the azure devops pipeline is altering the —bulk-seperator character argument. -> This is the first time I hear this, I think I've used the 

Appreciate if you can share the pipeline logs, less the secrets or connections string. It would be easier for me to investigate such that I need to know the agent you used such as linux or windows and the actual CLI commands generated by the pipeline.

**Comment by rdagumampan** [comment] 2021-09-12 21:38
And btw, maybe we can have short screen share sometime this week after work (5PM Denmark time) just to better understand the various use cases and issues you have encountered. Thanks again for reaching out.

**Comment by rdagumampan** [comment] 2021-09-12 21:42
I am also thinking maybe you can consider changing your development work flow. You may also create `dev`, `test`, `prod` git branches and instead direct the pipeline to use specific branch and deploying to a target environment. This can also enable the team members to make Pull Request (PR) to the branch with their local changes. HTH

**Comment by rdagumampan** [comment] 2021-09-12 22:27
I can confirm now that is a bug :/

![image](https://user-images.githubusercontent.com/5895952/133004777-be42e59a-8c9d-431e-a0b3-4b398a9b8e77.png)

**Comment by rdagumampan** [comment] 2021-12-19 22:25
Apparently the migration just executed as expected but the log messages was misleading because of wrong directory variable used in the log messages. This commit fixed the log message and will be part of next release.  See https://github.com/rdagumampan/yuniql/commit/61f516e495a74b98f4d46ae7b5943db5f9f040e8

```csharp
run -a -p "C:\play\yuniql-tutorials\yuniql-environment-aware" -c "Server=localhost,1400;Database=helloyuniql8;User Id=SA;Password=P@ssw0rd!" -k "ENVIRONMENT=PROD" --environment production --debug
```

```bash
INF   2021-12-19 22:10:44Z   Found 1 script files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.00
  + setup-views.sql
DBG   2021-12-19 22:10:44Z   Replaced token ENVIRONMENT with PROD
DBG   2021-12-19 22:10:44Z   Executing sql statement as part of : C:\play\yuniql-tutorials\yuniql-environment-aware\v0.00\setup-views.sql
DBG   2021-12-19 22:10:44Z   Executing statement 27F84F:
CREATE OR ALTER VIEW [dbo].[vw_employee_timesheets]
AS
        SELECT 'hello yuniql!' message;

        --SELECT E.employee_id, E.first_name, E.last_name, E.position, T.checkin_time_utc, T.checkout_time_utc
        --FROM [HRDB-PROD].[dbo].[employees] E
        --INNER JOIN [PAYROLLDB-PROD].[dbo].[timesheets] T
        --ON E.employee_id = t.employee_id
DBG   2021-12-19 22:10:44Z   Statement 27F84F executed in 13 ms
INF   2021-12-19 22:10:44Z   Executed script file C:\play\yuniql-tutorials\yuniql-environment-aware\v0.00\setup-views.sql.
INF   2021-12-19 22:10:44Z   Found 0 bulk files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.00
...
...
DBG   2021-12-19 22:10:44Z   Executing statement 045A64:

INSERT INTO [dbo].[__yuniql_schema_version] ([version], [applied_on_utc], [applied_by_user], [applied_by_tool], [applied_by_tool_version], [status], [duration_ms], [checksum], [failed_script_path], [failed_script_error], [additional_artifacts])
VALUES ('v0.00', GETUTCDATE(), SUSER_SNAME(), 'yuniql-cli', 'v1.0.0.0', 'Successful', '195', 'WIP', '', '', '');

DBG   2021-12-19 22:10:44Z   Statement 045A64 executed in 5 ms
INF   2021-12-19 22:10:44Z   Completed migration to version C:\play\yuniql-tutorials\yuniql-environment-aware\v0.00 in 195 ms
INF   2021-12-19 22:10:44Z   Found 0 script files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_development
INF   2021-12-19 22:10:44Z   Found 0 bulk files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_development
INF   2021-12-19 22:10:44Z   Found 1 script files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_production
  + setup-views.sql
DBG   2021-12-19 22:10:44Z   Executing sql statement as part of : C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_production\setup-views.sql
DBG   2021-12-19 22:10:44Z   Executing statement DA16E9:
CREATE OR ALTER VIEW [dbo].[vw_employee_timesheets]
AS
        SELECT 'hello yuniql from PROD!' message;

        --SELECT E.employee_id, E.first_name, E.last_name, E.position, T.checkin_time_utc, T.checkout_time_utc
        --FROM [HRDB-PROD].[dbo].[employees] E
        --INNER JOIN [PAYROLLDB-PROD].[dbo].[timesheets] T
        --ON E.employee_id = t.employee_id
DBG   2021-12-19 22:10:44Z   Statement DA16E9 executed in 75 ms
INF   2021-12-19 22:10:44Z   Executed script file C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_production\setup-views.sql.
INF   2021-12-19 22:10:44Z   Found 0 bulk files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_production
INF   2021-12-19 22:10:44Z   Found 0 script files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_test
INF   2021-12-19 22:10:44Z   Found 0 bulk files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01\_test
INF   2021-12-19 22:10:44Z   Found 0 script files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01
INF   2021-12-19 22:10:45Z   Found 0 bulk files on C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01
...
...
DBG   2021-12-19 22:10:45Z   Executing statement 915447:

INSERT INTO [dbo].[__yuniql_schema_version] ([version], [applied_on_utc], [applied_by_user], [applied_by_tool], [applied_by_tool_version], [status], [duration_ms], [checksum], [failed_script_path], [failed_script_error], [additional_artifacts])
VALUES ('v0.01', GETUTCDATE(), SUSER_SNAME(), 'yuniql-cli', 'v1.0.0.0', 'Successful', '332', 'WIP', '', '', '');

DBG   2021-12-19 22:10:45Z   Statement 915447 executed in 6 ms
INF   2021-12-19 22:10:45Z   Completed migration to version C:\play\yuniql-tutorials\yuniql-environment-aware\v0.01 in 332 ms
```

**Closed by rdagumampan** 2021-12-19 22:25 UTC
Labels: bug, community-feedback, state: working-on-it
