### ISSUE TITLE
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/'.

### ISSUE THREAD

**Issue by edisaac** [rdagumampan/yuniql#270] opened 2022-05-20 04:48 UTC
Whe using docker linux  
```
FROM pull yuniql/yuniql:linux-x64-1.2.25
COPY . ./db  

ENTRYPOINT ["dotnet", "yuniql.dll", "verify", "-p", "db"]

```
it shows the next error

A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, specify the appropriate framework in /app/yuniql.runtimeconfig.json.
##[error]A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/app/'.
##[error]Failed to run as a self-contained app. If this should be a framework-dependent app, specify the appropriate framework in /app/yuniql.runtimeconfig.json.
##[error]The process '/usr/bin/docker' failed with exit code 131

**Comment by rdagumampan** [comment] 2022-05-21 19:23
@edisaac, thanks for reaching out. I am able to reproduce the bug and I can confirm this behaviour. Meanwhile, I tested `1.1.55` tag and it works. Please watch out for next release where we can fix this.

```docker file
FROM yuniql/yuniql:linux-x64-1.1.55
COPY . ./db
```

```bash
docker network create --driver bridge sqlvnet

docker run --rm --name sqlserver --network sqlvnet -d -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=P@ssw0rd!" -p 1400:1433 -d mcr.microsoft.com/mssql/server:2017-latest

docker run --rm --name sqlserversample --network sqlvnet sqlserver-example --platform sqlserver -d -a -c "Server=sqlserver,1433;Database=yuniqldb;User Id=SA;Password=P@ssw0rd!;TrustServerCertificate=True"

docker rm sqlserver -f
docker network rm sqlvnet
```

P.S. Please star our repo ICYMI. It goes a long way in getting better stats and helping more people discover this tool :) Thanks!

**Comment by rdagumampan** [comment] 2022-05-22 04:45
Similar issue #190

**Comment by rdagumampan** [comment] 2022-05-23 18:48
Closed. Released in v1.3.10. A new docker images is available:
- `yuniql/yuniql:linux-x64-1.3.10`  The base image
- `yuniql/cli:linux-x64-1.3.10`  Stand alone container for running migrations just like a CLI

```
docker run --rm -v c:/play/yuniql/samples/basic-postgresql-sample:/data yuniql/cli:linux-x64-1.3.10 run --platform postgresql -d  -c "<your-connection-string>"
```
```
docker run --rm yuniql/cli:linux-x64-1.3.10 list --platform postgresql -d  -c "<your-connection-string>"
```
![image](https://user-images.githubusercontent.com/5895952/169886120-f3fb2138-f82b-40f8-95ba-0ac40d2ac156.png)

```
docker run --rm -v c:/play/yuniql/samples/basic-postgresql-sample:/data yuniql/cli:linux-x64-1.3.10 erase --platform postgresql -d  -c "<your-connection-string>" --force
```

**Closed by rdagumampan** 2022-05-23 18:48 UTC
Labels: bug, state: investigating, community-feedback, state: ready-for-release

**Comment by edisaac** [comment] 2022-05-29 23:18
thanks a lot , i was using  rdagumampan/yuniql:latest , now im using yuniql/yuniql:linux-x64-1.1.55.  for Some reason the last one give a TLS error, but i think is my network or my database (sql 2008), i will check it later.

**Comment by rdagumampan** [comment] 2022-05-30 03:28
Hi @edisaac , try to use `v1.3.10` base image or `v1.3.15` CLI. 
- `yuniql` is not tested with SqlServer 2008 :), i hope it works with your instance
- Due to migration to the new Microsoft driver for SQL Sever, the Encrypted connection is now enabled by default. An error described below will ne thrown in your next migration run targeting SqlServer. To resolve this, you may need to install necessary client certificate. Alternatively, you may use self-signed certificate by adding `TrustServerCertificate=True` in the connection string or ultimately set `Encrypt=False` as it is before.

> ERR 2022-05-08 12:28:35Z Failed to execute run function. A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
https://weblog.west-wind.com/posts/2021/Dec/07/Connection-Failures-with-MicrosoftDataSqlClient-4-and-later
