### ISSUE TITLE
failed database updates should ideally fail with a non-zero exit code

### ISSUE THREAD

**Issue by CosyStudios** [rdagumampan/yuniql#198] opened 2021-02-24 13:55 UTC
Trying to integrate with Jenkins as part of a deployment. 
Noted the user provided doesnt have the rights to update tables, my fault....
As a result the updates fail but Jenkins doesnt abort the rest of the process. 
would something like do yuniqlthing || exit 0 work? 

The below response might help clarify
`INF   2021-02-24 13:19:04Z   Run configuration: 
{
  "isInitialized": true,
  "workspace": "setup/dbupdates",
  "platform": "postgresql",
  "connectionString": "<sensitive-data-redacted>",
  "isAutoCreateDatabase": false,
  "targetVersion": null,
  "tokens": [],
  "isVerifyOnly": false,
  "bulkSeparator": ",",
  "bulkBatchSize": 0,
  "commandTimeout": 30,
  "isDebug": false,
  "appliedByTool": "yuniql-cli",
  "appliedByToolVersion": "1.1.55.0",
  "environment": null,
  "metaSchemaName": null,
  "metaTableName": null,
  "isContinueAfterFailure": false,
  "transactionMode": "session",
  "isRequiredClearedDraft": false,
  "isForced": false
}
INF   2021-02-24 13:19:05Z   No explicit target version requested. We'll use latest available locally v0.01 on setup/dbupdates.
INF   2021-02-24 13:19:06Z   The schema version tracking table is up to date for doris on localhost.
INF   2021-02-24 13:19:06Z   Transaction created for current session. This migration run will be executed in a shared connection and transaction context.
INF   2021-02-24 13:19:06Z   Found 0 script files on setup/dbupdates/_pre
INF   2021-02-24 13:19:06Z   Found 0 script files on setup/dbupdates/_pre
INF   2021-02-24 13:19:06Z   Executed script files on setup/dbupdates/_pre
INF   2021-02-24 13:19:06Z   Found 0 script files on setup/dbupdates
INF   2021-02-24 13:19:06Z   Found 0 script files on setup/dbupdates/v0.00
INF   2021-02-24 13:19:06Z   Completed migration to version setup/dbupdates/v0.00 in 4 ms
INF   2021-02-24 13:19:06Z   Found 2 script files on setup/dbupdates
  + 02-setup-noticefeed-table.sql
  + 01-setup-noticefeed-seq.sql
ERR   2021-02-24 13:19:06Z   Failed to execute run function. Migration of version v0.01 was running in transaction and has failed while attempting to execute script file setup/dbupdates/v0.01/01-setup-noticefeed-seq.sql due to error "(0x80004005) Error 42501: must be member of role "postgres". Exception data: Severity: ERROR, InvariantSeverity: ERROR, SqlState: 42501, MessageText: must be member of role "postgres", File: acl.c, Line: 4962, Routine: check_is_member_of_role". The target database will initiate a rollback attempt to revert all applicable DML and DDL changes. The database auto-created will be kept but would be empty.
Diagnostics stack trace captured a Migration of version v0.01 was running in transaction and has failed while attempting to execute script file setup/dbupdates/v0.01/01-setup-noticefeed-seq.sql due to error "(0x80004005) Error 42501: must be member of role "postgres". Exception data: Severity: ERROR, InvariantSeverity: ERROR, SqlState: 42501, MessageText: must be member of role "postgres", File: acl.c, Line: 4962, Routine: check_is_member_of_role". The target database will initiate a rollback attempt to revert all applicable DML and DDL changes. The database auto-created will be kept but would be empty. 42501: must be member of role "postgres"
If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues.
------------------------------------------------------------------------
DB updates complete, versions present in database as follows
------------------------------------------------------------------------
Running yuniql v1.1.55 for linux-x64
Copyright 2019 (C) Rodel E. Dagumampan. Apache License v2.0
Visit https://yuniql.io for documentation & more samples`

**Comment by rdagumampan** [comment] 2021-02-24 16:52
@CosyStudios, thank you for your feedback and interest un yuniql. I hope I understand you question right... When run failed, yuniql exits with a non-zero code which is default to 1. This is help in very use case you have where we can control the pipelines. 

Quick look at code looks ok...I will investigate this and get back to you...

```csharp
        private int OnException(Exception exception, string headerMessage, bool debug)
        {
            var stackTraceMessage = debug ? exception.ToString().Replace(exception.Message, string.Empty) 
                : $"{exception.Message} {exception.InnerException?.Message}";
            
            _traceService.Error($"{headerMessage}. {exception.Message}{Environment.NewLine}" +
                $"Diagnostics stack trace captured a {stackTraceMessage}{Environment.NewLine}" +
                $"If you think this is a bug, please report an issue here https://github.com/rdagumampan/yuniql/issues."); //TODO: create global constants for url
            return 1;
        }
```

**Comment by rdagumampan** [comment] 2021-05-15 19:15
Hi @CosyStudios , im closing this ticket as I'm unable to reproduce the error. I tested on console window and reprint the error code. It looks like it works as expected. Please commend or reopen if you have more information. Thanks for your feedback.

### Successful run
![image](https://user-images.githubusercontent.com/5895952/118375564-a3200680-b5c2-11eb-8994-073cb208f037.png)

### Failed run:
![image](https://user-images.githubusercontent.com/5895952/118375548-88e62880-b5c2-11eb-8717-f336a2b34eb2.png)

**Closed by rdagumampan** 2021-05-15 19:15 UTC
Labels: community-feedback, investigating, platform-postgresql

**Comment by CosyStudios** [comment] 2021-05-26 14:45
no worries rda. I think the issue was more with my Jenkins setup which im not too familiar with. Regardless, I now have a successful working method for yuniql in my project and its awesome. Great work

**Comment by rdagumampan** [comment] 2021-05-26 20:17
@CosyStudios, thanks and good to know you're able to figure out. If you haven't done yet, appreciate if you could give our re a Star. Br, Rodel
