### ISSUE TITLE
Environment-aware migration not working.

### ISSUE THREAD

**Issue by Not-That-Guy** [rdagumampan/yuniql#208] opened 2021-06-30 04:59 UTC
Trying to get Environment-aware working but when I run scripts via Azure it is not finding the scripts, logs show the following

`2021-06-30T04:38:28.3972483Z INF   2021-06-30 04:38:28Z   Completed migration to version D:\a\r1\a/_PaymentGatewayDb/db\v0.00 in 304 ms
2021-06-30T04:38:28.3995274Z INF   2021-06-30 04:38:28Z   Found 0 script files on D:\a\r1\a/_PaymentGatewayDb/db
2021-06-30T04:38:28.3996028Z INF   2021-06-30 04:38:28Z   Found 0 script files on D:\a\r1\a/_PaymentGatewayDb/db\v0.01\_development
2021-06-30T04:38:28.3998482Z INF   2021-06-30 04:38:28Z   Found 0 script files on D:\a\r1\a/_PaymentGatewayDb/db
2021-06-30T04:38:28.4000678Z INF   2021-06-30 04:38:28Z   Found 0 script files on D:\a\r1\a/_PaymentGatewayDb/db\v0.01\_production
2021-06-30T04:38:28.4002255Z INF   2021-06-30 04:38:28Z   Found 0 script files on D:\a\r1\a/_PaymentGatewayDb/db
2021-06-30T04:38:28.4003673Z INF   2021-06-30 04:38:28Z   Found 0 script files on D:\a\r1\a/_PaymentGatewayDb/db\v0.01\_test
2021-06-30T04:38:28.4005953Z INF   2021-06-30 04:38:28Z   Found 2 script files on D:\a\r1\a/_PaymentGatewayDb/db
2021-06-30T04:38:28.4006540Z   + 01-Populate_BusinesssRules.sql
2021-06-30T04:38:28.4007097Z   + 02-Create-Payments-Email.sql`

Its finding 0 scripts in the _development, _production and _test folders. My db folder is configured as follows:

![image](https://user-images.githubusercontent.com/28390532/123903895-1f6b7f00-d9a2-11eb-8a4f-3c0a45c7a83f.png)

Azure devops configured with 

![image](https://user-images.githubusercontent.com/28390532/123903990-475ae280-d9a2-11eb-94c8-e772cfcf40db.png)

I followed based on documentation and found the migration project under yuniql repos. I tried folder names _dev, _test, _prod - I've named all the scripts the same name, tried a few different configuration options, even tried to run this via CLI and same issue  0 scripts found every time. 

Everything else is running without an issue.

What am I missing here?

**Comment by rdagumampan** [comment] 2021-07-06 19:55
Hi @Not-That-Guy, thanks for reaching out and sorry for this uber late reply. Been out on summer holidays lately. Btw, can you please try with same casing such as `--debug --environment test` or `--debug --environment production`. Running this on Linux agents requires same casing because Linux is case sensitive.

Let me know what happens. Thanks.

**Comment by rdagumampan** [comment] 2021-09-06 19:26
@Not-That-Guy, I hope you are able to make this work or have found a work around. If this remains a bug, I would have time to investigate further this weekend. Thanks for your support and feedback.

**Comment by rdagumampan** [comment] 2021-09-12 22:29
I can confirm now that is a bug. Sorry for the inconvenience and I hope you found a work around. An alternative would be to use git branches to segment environments. For example, you can create `dev`, `test` and `production` branches.

![image](https://user-images.githubusercontent.com/5895952/133004802-73aacf00-d170-4d86-9be7-a715a466b0ba.png)

**Comment by rdagumampan** [comment] 2021-12-19 22:27
https://github.com/rdagumampan/yuniql/issues/214

**Comment by rdagumampan** [comment] 2021-12-19 22:28
Closing. Please refer to my closing comments here. Thanks for your feedback.
https://github.com/rdagumampan/yuniql/issues/214

**Closed by rdagumampan** 2021-12-19 22:28 UTC
Labels: bug, community-feedback, state: working-on-it
